<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>WinFormsStudentApp</RootNamespace>
    <AssemblyName>WinFormsStudentApp</AssemblyName>
    <Nullable>disable</Nullable>
  </PropertyGroup>
</Project>
